name: Eugene Ng
favicon: null
layout_spectrum: 0.8070950934197754
typography_spectrum: 0.7907033236697316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4563241482246667
  lightness: 0.5605292948894203
  saturation: 0.23546254402026534
  rhythmicContrast: 0.46869732975028455
purpose: []
