name: Eugene Ng
favicon: null
layout_spectrum: 0.8070950934197754
typography_spectrum: 0.7907033236697316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b090c'
    - '#8e8872'
    - '#f46554'
    - '#137c5b'
  brandStrength: 0.6875
  lightness: 0.5605292948894203
  saturation: 0.23546254402026534
  rhythmicContrast: 0.75
purpose: []
